### ISSUE TITLE
Repeat runs with collections adds duplicates

### ISSUE THREAD

**Issue by Aintaer** [metalsmith/collections#27] opened 2015-02-10 06:48 UTC
Currently, repeated calls to `metalsmith.build()` is non-idempotent because metalsmith-collections will find the same files that belongs to a collection, and add them to the same array as exists in memory from the previous run.

This is due to metalsmith storing collections in the global metadata object. Maybe it should empty out the collections arrays every time it runs?

My workaround right now is essentially

``` js
metalsmith.build(function(err, files) {
  if (err) throw err;
  metalsmith.metadata(origMetadata);
});
```

**Comment by MoOx** [comment] 2015-04-27 06:19
Same issue for partial rebuild with metalsmith-watch that is using run() method.

**Comment by venomgfx** [comment] 2015-07-23 08:44
I'm also getting this issue.

Couldn't get the workaround that @Aintaer mentions to work either. Do you have an idea what am I doing wrong? Thanks!

```javascript
var siteBuild = metalsmith(__dirname)
	.use(paths())
	.use(relative())
	.metadata({
		site: {
			title: 'Site Title'
		}
	})
	.use(markdown())
	.use(collections({
		apples: {
			metadata: {
				name: 'Apples',
				description: ''
			}
		},
		oranges: {
			metadata: {
				name: 'Oranges',
				description: ''
			}
		}
	})
	)
	.use(templates( 'jade'))
	.use(sass())
	.use(watch({
		paths: {
			"src/**/*": "**/*.md",
			"templates/**/*": "**/*.md"
		},
		livereload: true
		})
	)
	.destination('./build')
	.build(function (err) {
		if (err) throw err;
	});
```

**Comment by deltamualpha** [comment] 2015-07-23 12:23
I solved this with a fork that deletes the collections metadata before re-adding articles to collections -- https://github.com/deltamualpha/metalsmith-collections/commit/a3d5db626647ea3f0fbe01d4b9151d0cd99108b4 -- but I don't know if that's the right answer overall.

**Comment by venomgfx** [comment] 2015-07-23 13:09
Thanks @deltamualpha ! My current workaround is to just use half the collection when looping through it in the template, but yeah would be nice if this got fixed for real. It's pretty strange not to find more people with the same issue, collections are quite basic functionality.

**Comment by deltamualpha** [comment] 2015-07-23 13:26
@venomgfx I think part of it is that from what I've seen, Segment thinks that watchers as part of the build pipeline are a bad idea, and that the rebuild logic (and serving) should be external to the Metalsmith object.  I'm considering re-writing my build path to work this way. Some third-party plugins have logic that handles watchers correctly, but most of the first-party ones don't.

**Comment by venomgfx** [comment] 2015-07-23 13:30
@deltamualpha Ah that makes sense yes. Perhaps it's worth looking into [gulp-metalsmith](https://www.npmjs.com/package/gulp-metalsmith). So we watch outside of the metalsmith build pipeline. Will try it out. Thanks a lot for your feedback!

**Comment by mplewis** [comment] 2015-08-20 04:46
@deltamualpha: that fix works for me. Thanks for your help!

**Comment by razvanc87** [comment] 2015-08-22 04:01
guys, I have the same problem with `metalsmith-watch` so I started poking at the source code. I'm not sure if I'm doing it correctly but, based on the `filename` property I managed to verify if the file is already in the collections or not... seems to work in my case (and for now)... but I just have about 3 weeks `nodejs` experience and most of the time I have no idea what I'm doing... here's the diff:

```diff
diff -u index.js ../../blog/node_modules/metalsmith-collections/lib/index.js 
--- index.js    2015-08-22 04:53:38.962863606 +0100
+++ ../../blog/node_modules/metalsmith-collections/lib/index.js 2015-08-22 04:51:11.137564810 +0100
@@ -32,8 +32,26 @@
      * Find the files in each collection.
      */
 
+    var in_collections;
     Object.keys(files).forEach(function(file){
       debug('checking file: %s', file);
+
+      var collections = metadata.collections;
+      if (collections) {
+        in_collections = Object.keys(collections).map(function(collection) {
+          return collections[collection].filter(function(data) {
+            return (file === data.filename);
+          });
+        });
+        in_collections = [].concat.apply([], in_collections);
+      }
+
+      // and from outer body return if file already in collections
+      if (in_collections && in_collections.length === 1) {
+        debug('already in collections, skipping: %s', in_collections[0].filename);
+        return;
+      }
+
       var data = files[file];
       match(file, data).forEach(function(key){
         if (key && keys.indexOf(key) < 0){
```

maybe someone with more experience can pitch in and let us know if this works?

**Comment by mplewis** [comment] 2015-08-23 17:08
@razvanc87: I see the same behavior.

Some of the root cause of this problem is that metalsmith-watch only passes documents into the pipeline that have changed. If you have source files set to refresh only themselves, while template files refresh all source files, you will see differences in behavior between the two.

**Comment by razvanc87** [comment] 2015-08-23 20:44
I've... sopped trying to figure out what's happening and instead am using `browsersync`, the CLI alongside `nodemon` to keep everything in sync, instead of relaying on `metalsmith` plugins... Hope this gets fixed some day though.

**Comment by deltamualpha** [comment] 2015-08-24 18:38
Yeah, `metalsmith-watch` implements some special-casing to make collections not explore immediately, but it's not perfect, and a very good example of why in-band watch & rebuild plugins might be a bad idea.

**Comment by razvanc87** [comment] 2015-08-24 18:52
Well... they are a bad idea because it's hard to deal with mutable state, but as far as efficiency goes... I'd rather have them then not (if it wouldn't interfere and make a mess of the state).

Whereas rebuilding from scratch with all the imports, etc. takes about 1-2 seconds, with in-band watch, this can be almost real-time, because you're also rebuilding basically one file at a time instead of the whole directory... which is quite nice. Unfortunately I couldn't make it work with this collections plugin. If I do get a better understanding I definitely will poke at this again :).

**Comment by cameronjroe** [comment] 2015-10-24 01:23
+1

**Comment by lapidus** [comment] 2015-10-27 20:50
+1

**Comment by woodyrew** [comment] 2015-10-30 19:43
I used to have this issue with `watch`, however using `nodemon` makes life more simple and closer to real world building.

**Comment by chiefy** [comment] 2016-01-11 01:53
:+1: fixed it locally by checking the `metadata[key]` array for the same file before adding it. A real fix would be nice.

**Comment by spacedawwwg** [comment] 2016-03-23 23:07
:+1: +1

**Comment by spacedawwwg** [comment] 2016-03-23 23:21
Forked this for now and added the `metadata[key]` fix mentioned by @deltamualpha

https://github.com/spacedawwwg/metalsmith-collections

use this forked version by adding 

```JSON
"devDependencies": {
    "metalsmith-collections": "spacedawwwg/metalsmith-collections"
}
```
to your `package.json`

I've submitted a pull request, but I'll keep the fork updated until this finally gets fixed (it has been a year since this issue was posted)

**Comment by AndyOGo** [comment] 2016-08-26 00:30
Another quickfix is to monkey patch the build method, like:

```js
var build = metalsmith.build;
metalsmith.build = function() {
  build.apply(ms, arguments)
  ms.metadata(originalMeta));
}
```

This whipes it after every build and works with `metalsmith-browser-sync` too

**Comment by genexp** [comment] 2016-11-20 23:08
Thanks @spacedawwwg that works great.

**Comment by ReedD** [comment] 2016-12-13 05:25
Here's another fix to force the metadata to reset every build. Similar idea to @AndyOGo.
```
metalsmith('./src')
	.use((files, metalsmith, done) => {
		setImmediate(done);
		metalsmith.metadata({
			site: {},
			package: require( './package.json')
		});
	})
```

**Comment by edhenderson** [comment] 2018-04-19 03:46
Did this ever get fixed @spacedawwwg ? BTW - thanks for the temp fix.

**Comment by rludgero** [comment] 2018-12-20 14:30
To avoid this issue, install by `https` the new version of metalsmith-collections.

```
npm install --save-dev git+https://github.com/segmentio/metalsmith-collections.git
```

This will be install the latest version of plugin, since metalsmith org still does not have permission to push to `NPM` yet.

**Closed** 2022-02-02 00:17 UTC

**Comment by AndyOGo** [comment] 2022-02-02 00:28
@webketje Why did you close this.
Is it fixed or not?

**Comment by webketje** [comment] 2022-02-02 00:34
@AndyOGo please see the commit 891b24c which adds a test for this. In the latest published version, I did quite some refactoring and suspected I incidentally fixed it (I think it was even fixed long ago but just in a messy way and without updating this issue)
See also https://github.com/metalsmith/collections/blob/master/lib/index.js#L91
