### ISSUE TITLE
Multiple builds break the plugin

### ISSUE THREAD

**Issue by rstacruz** [metalsmith/collections#78] opened 2017-10-11 23:17 UTC
The plugin isn't idempotent, running it twice will screw up the metadata.

```js
app = metalsmith()
  .use(collections({ articles: { ... } })
  .build(done => ...)
  .build(done => ...)
```

The workaround is to create a middleware that clears up metadata:

```js

app = metalsmith()
  .use((files, ms, done) => {
    ms.metadata({ articles: [] })
    done()
  })
  .use(collections({ articles: { ... } })
  .build(done => ...)
  .build(done => ...)
```

**Comment by dwightjack** [comment] 2018-02-07 08:03
👍 On this.

I've spent some time on this issue. In my case (using `collection: ` in frontmatter, collections gets populated automatically. 

My solution is as follows:

```js
app = metalsmith()
  .use((files, ms, done) => {
    const metadata = ms.metadata()
    const { collections } = metadata
    if (collections) {
      Object.keys(collections).forEach((k) => {
        metadata[k] = [];
      });
    }
    done()
  })
  .use(collections({ articles: { ... } })
  .build(done => ...)
  .build(done => ...)
```

**Comment by webketje** [comment] 2022-02-02 00:39
Closing as this is a duplicate of #27

**Closed by webketje** 2022-02-02 00:39 UTC
